services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban_db
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

